---
# ansible-playtbook k8s-node-setup.yml

- name: k8s Node Setup v2
  hosts: "*"
  tasks:
    - name: install needed Operating System packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: install docker-ce yum repo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: install docker-ce using yum
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - docker-ce

    - name: Start and enable docker service.
      service:
        name: docker
        state: started
        enabled: yes

    - name: Disable swap space on nodes(systems).
      command: swapoff -a

    - name: Ensure SELinux is set to permissive mode.
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=permissive

    - name: Disable selinux on systems.
      command: setenforce 0

    - name: copy k8s repo file to node. See script for details on how this was implemented.
      copy:
        src: scripts/install_k8s_tools.sh
        dest: /tmp/install_k8s_tools.sh
        owner: root
        group: root
        mode: 0774

    - name: Run install_k8s_tools.sh script (check script to see what is being done.)
      command: /tmp/install_k8s_tools.sh

    - name: Enable kubernetes yum repo
      command: yum-config-manager --enable kubernetes

    - name: install kubelet kubeadm kubectl
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable services kubelet, if not enabled
      service:
        name: kubelet
        state: started
        enabled: yes

    - name: Disable services kubelet, if not enabled
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: copy sysctl.conf updated file to node (fixes k8s init error.)
      copy:
        src: files/sysctl.conf
        dest: /etc/sysctl.conf
        owner: root
        group: root
        mode: 0644

    - name: Refresh sysctl settings
      command: sysctl -p
