---
# ansible-playtbook k8s-node-setup.yml

- name: k8s Node Setup
  hosts: "*"
  tasks:
    - name: Disable swap on nodes.
      command: swapoff -a

    - name: copy k8s repo file to node
      copy:
        src: scripts/install_k8s_tools.sh
        dest: /tmp/install_k8s_tools.sh
        owner: root
        group: root
        mode: 0774

    - name: Run install_k8s_tools.sh script
      command: /tmp/install_k8s_tools.sh

    - name: Enable kubernetes yum repo
      command: yum-config-manager --enable kubernetes

    - name: install kubelet kubeadm kubectl
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - kubelet
        - kubeadm
        - kubectl

    - name: copy sysctl.conf updated file to node
      copy:
        src: files/sysctl.conf
        dest: /etc/sysctl.conf
        owner: root
        group: root
        mode: 0644

    - name: Refresh sysctl settings
      command: sysctl -p
      
    - name: Enable services kubelet, if not enabled
      service:
        name: kubelet
        state: started
        enabled: yes

    - name: Disable/stop firewalld services kubelet, if not enabled
      service:
        name: firewalld
        state: stopped
        enabled: no
